// <auto-generated />
using System;
using BackendCoopSoft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendCoopSoft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126031041_updateHistoricoTrabajador")]
    partial class updateHistoricoTrabajador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendCoopSoft.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asistencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool>("EsEntrada")
                        .HasColumnType("bit")
                        .HasColumnName("es_entrada");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Capacitacion", b =>
                {
                    b.Property<int>("IdCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_capacitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCapacitacion"));

                    b.Property<byte[]>("ArchivoCertificado")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("archivo_certificado");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int")
                        .HasColumnName("carga_horaria");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("institucion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdCapacitacion");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Capacitacion");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cargo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdOficina")
                        .HasColumnType("int")
                        .HasColumnName("id_oficina");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_cargo");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdOficina");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Clasificador", b =>
                {
                    b.Property<int>("IdClasificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_clasificador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClasificador"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("ValorCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("valor_categoria");

                    b.HasKey("IdClasificador");

                    b.HasIndex("Categoria", "ValorCategoria")
                        .IsUnique();

                    b.ToTable("Clasificador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Concepto", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_concepto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConcepto"));

                    b.Property<bool>("AplicaAguinaldo")
                        .HasColumnType("bit")
                        .HasColumnName("aplica_aguinaldo");

                    b.Property<bool>("AplicaAportes")
                        .HasColumnType("bit")
                        .HasColumnName("aplica_aportes");

                    b.Property<bool>("AplicaMensual")
                        .HasColumnType("bit")
                        .HasColumnName("aplica_mensual");

                    b.Property<bool>("AplicaPrima")
                        .HasColumnType("bit")
                        .HasColumnName("aplica_prima");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EditablePorUsuario")
                        .HasColumnType("bit")
                        .HasColumnName("es_editable");

                    b.Property<bool>("EsVisibleEnReporte")
                        .HasColumnType("bit")
                        .HasColumnName("es_visible");

                    b.Property<int>("IdMetodoCalculo")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_calculo");

                    b.Property<int>("IdNaturaleza")
                        .HasColumnType("int")
                        .HasColumnName("id_naturaleza");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NombreConcepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_concepto");

                    b.Property<int>("OrdenCalculo")
                        .HasColumnType("int")
                        .HasColumnName("orden_calculo");

                    b.Property<decimal?>("Porcentaje")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("porcentaje");

                    b.Property<bool>("TipoConcepto")
                        .HasColumnType("bit")
                        .HasColumnName("tipo_concepto");

                    b.HasKey("IdConcepto");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdMetodoCalculo");

                    b.HasIndex("IdNaturaleza");

                    b.HasIndex("OrdenCalculo");

                    b.ToTable("Concepto");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<byte[]>("ArchivoPdf")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("archivo_pdf");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdPeriodoPago")
                        .HasColumnType("int")
                        .HasColumnName("id_periodo_pago");

                    b.Property<int>("IdTipoContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_contrato");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_contrato");

                    b.HasKey("IdContrato");

                    b.HasIndex("IdPeriodoPago");

                    b.HasIndex("IdTipoContrato");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Falta", b =>
                {
                    b.Property<int>("IdFalta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_falta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFalta"));

                    b.Property<byte[]>("ArchivoJustificativo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("archivo_justificativo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTipoFalta")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_falta");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.HasKey("IdFalta");

                    b.HasIndex("IdTipoFalta");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Falta");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.FormacionAcademica", b =>
                {
                    b.Property<int>("IdFormacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_formacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormacion"));

                    b.Property<int>("AnioGraduacion")
                        .HasColumnType("int")
                        .HasColumnName("anio_graduacion");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("institucion");

                    b.Property<string>("NivelEstudios")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nivel_estudios");

                    b.Property<string>("NroRegistroProfesional")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nro_registro_profesional");

                    b.Property<string>("TituloObtenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("titulo_obtenido");

                    b.HasKey("IdFormacion");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Formacion_Academica");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoFalta", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdFalta")
                        .HasColumnType("int")
                        .HasColumnName("id_falta");

                    b.Property<int>("UsuarioModificoId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdFalta");

                    b.HasIndex("UsuarioModificoId");

                    b.ToTable("Historico_Falta");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoPersona", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accion");

                    b.Property<string>("ApartadosModificados")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apartados_modificados");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("UsuarioModificoId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdPersona");

                    b.HasIndex("UsuarioModificoId");

                    b.ToTable("Historico_Persona");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoPlanilla", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int")
                        .HasColumnName("id_planilla");

                    b.Property<int>("UsuarioModificoId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdPlanilla");

                    b.HasIndex("UsuarioModificoId");

                    b.ToTable("Historico_Planilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoTrabajador", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("accion");

                    b.Property<string>("ApartadosModificados")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("apartados_modificados");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<int>("UsuarioModificoId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdTrabajador");

                    b.HasIndex("UsuarioModificoId");

                    b.ToTable("Historico_Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoTrabajadorPlanilla", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdTrabajadorPlanilla")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador_planilla");

                    b.Property<int>("UsuarioModificoId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdTrabajadorPlanilla");

                    b.HasIndex("UsuarioModificoId");

                    b.ToTable("Historico_Trabajador_Planilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoUsuario", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("accion");

                    b.Property<string>("ApartadosModificados")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("apartados_modificados");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("UsuarioModificoId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioModificoId");

                    b.ToTable("Historico_Usuario");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_horario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time")
                        .HasColumnName("hora_entrada");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdTrabajador", "DiaSemana")
                        .IsUnique();

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HuellaDactilar", b =>
                {
                    b.Property<int>("IdHuella")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_huella");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHuella"));

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("huella");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.HasKey("IdHuella");

                    b.HasIndex("IdPersona");

                    b.ToTable("Huella_Dactilar");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.LogAcceso", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<DateTime>("FechaLogin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_login");

                    b.Property<DateTime?>("FechaLogout")
                        .HasColumnType("date")
                        .HasColumnName("fecha_logout");

                    b.Property<TimeSpan>("HoraLogin")
                        .HasColumnType("time")
                        .HasColumnName("hora_login");

                    b.Property<TimeSpan?>("HoraLogout")
                        .HasColumnType("time")
                        .HasColumnName("hora_logout");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Log_Acceso");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Oficina", b =>
                {
                    b.Property<int>("IdOficina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_oficina");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOficina"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("telefono");

                    b.HasKey("IdOficina");

                    b.ToTable("Oficina");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("CarnetIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("carnet_identidad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("foto");

                    b.Property<bool>("Genero")
                        .HasColumnType("bit")
                        .HasColumnName("genero");

                    b.Property<int>("IdNacionalidad")
                        .HasColumnType("int")
                        .HasColumnName("id_nacionalidad");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("segundo_nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdNacionalidad");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Planilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_planilla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanilla"));

                    b.Property<bool>("EstaCerrada")
                        .HasColumnType("bit")
                        .HasColumnName("esta_cerrada");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("date")
                        .HasColumnName("fecha_cierre");

                    b.Property<int>("Gestion")
                        .HasColumnType("int")
                        .HasColumnName("gestion");

                    b.Property<int>("IdTipoPlanilla")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_planilla");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("mes");

                    b.Property<DateTime>("PeriodoDesde")
                        .HasColumnType("date")
                        .HasColumnName("periodo_desde");

                    b.Property<DateTime>("PeriodoHasta")
                        .HasColumnType("date")
                        .HasColumnName("periodo_hasta");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdTipoPlanilla", "Gestion", "Mes")
                        .IsUnique();

                    b.ToTable("Planilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("date")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdEstadoSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_solicitud");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Trabajador", b =>
                {
                    b.Property<int>("IdTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrabajador"));

                    b.Property<bool>("EstadoTrabajador")
                        .HasColumnType("bit")
                        .HasColumnName("estado_trabajador");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<decimal>("HaberBasico")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("haber_basico");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int")
                        .HasColumnName("id_cargo");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.HasKey("IdTrabajador");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.TrabajadorPlanilla", b =>
                {
                    b.Property<int>("IdTrabajadorPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador_planilla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrabajadorPlanilla"));

                    b.Property<bool>("AfiliadoCaja")
                        .HasColumnType("bit")
                        .HasColumnName("afiliado_caja");

                    b.Property<bool>("AfiliadoGestora")
                        .HasColumnType("bit")
                        .HasColumnName("afiliado_gestora");

                    b.Property<bool>("AfiliadoProvivienda")
                        .HasColumnType("bit")
                        .HasColumnName("afiliado_provivenda");

                    b.Property<int>("AntiguedadMeses")
                        .HasColumnType("int")
                        .HasColumnName("antiguedad_meses");

                    b.Property<int>("DiasTrabajados")
                        .HasColumnType("int")
                        .HasColumnName("dias_trabajados");

                    b.Property<bool>("EsAportante")
                        .HasColumnType("bit")
                        .HasColumnName("es_aportante");

                    b.Property<decimal>("HaberBasicoMes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("haber_basico_mes");

                    b.Property<int>("HorasTrabajadas")
                        .HasColumnType("int")
                        .HasColumnName("horas_trabajadas");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int")
                        .HasColumnName("id_planilla");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("NombreCargoMes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_cargo_mes");

                    b.HasKey("IdTrabajadorPlanilla");

                    b.HasIndex("IdPlanilla");

                    b.HasIndex("IdTrabajador", "IdPlanilla")
                        .IsUnique();

                    b.ToTable("Trabajador_Planilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.TrabajadorPlanillaValor", b =>
                {
                    b.Property<int>("IdTrabajadorPlanillaValor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador_planilla_valor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrabajadorPlanillaValor"));

                    b.Property<bool>("EsManual")
                        .HasColumnType("bit")
                        .HasColumnName("es_manual");

                    b.Property<int>("IdConcepto")
                        .HasColumnType("int")
                        .HasColumnName("id_concepto");

                    b.Property<int>("IdTrabajadorPlanilla")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador_planilla");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("observacion");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdTrabajadorPlanillaValor");

                    b.HasIndex("IdConcepto");

                    b.HasIndex("IdTrabajadorPlanilla", "IdConcepto")
                        .IsUnique();

                    b.ToTable("Trabajador_Planilla_Valor");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("EstadoUsuario")
                        .HasColumnType("bit")
                        .HasColumnName("estado_usuario");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Licencia", b =>
                {
                    b.Property<int>("IdLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_licencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLicencia"));

                    b.Property<byte[]>("ArchivoJustificativo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("archivo_justificativo");

                    b.Property<decimal>("CantidadJornadas")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cantidad_jornadas");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("IdEstadoLicencia")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_licencia");

                    b.Property<int>("IdTipoLicencia")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_licencia");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int")
                        .HasColumnName("id_trabajador");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion");

                    b.HasKey("IdLicencia");

                    b.HasIndex("IdEstadoLicencia");

                    b.HasIndex("IdTipoLicencia");

                    b.HasIndex("IdTrabajador");

                    b.ToTable("Licencia");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Asistencia", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Capacitacion", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Capacitaciones")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Cargo", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Oficina", "Oficina")
                        .WithMany("Cargos")
                        .HasForeignKey("IdOficina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficina");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Concepto", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "MetodoCalculo")
                        .WithMany("MetodosCalculoConcepto")
                        .HasForeignKey("IdMetodoCalculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Clasificador", "Naturaleza")
                        .WithMany("NaturalezasConcepto")
                        .HasForeignKey("IdNaturaleza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoCalculo");

                    b.Navigation("Naturaleza");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Contrato", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "PeriodoPago")
                        .WithMany("PeriodosPago")
                        .HasForeignKey("IdPeriodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Clasificador", "TipoContrato")
                        .WithMany("TiposContrato")
                        .HasForeignKey("IdTipoContrato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Contratos")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PeriodoPago");

                    b.Navigation("TipoContrato");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Falta", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "TipoFalta")
                        .WithMany("Faltas")
                        .HasForeignKey("IdTipoFalta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Faltas")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoFalta");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.FormacionAcademica", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("FormacionesAcademicas")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoFalta", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Falta", "Falta")
                        .WithMany("HistoricoFaltas")
                        .HasForeignKey("IdFalta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Usuario", "UsuarioModifico")
                        .WithMany("HistoricosFaltaModificadosPorMi")
                        .HasForeignKey("UsuarioModificoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Falta");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoPersona", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Persona", "Persona")
                        .WithMany("HistoricoPersonas")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Usuario", "UsuarioModifico")
                        .WithMany("HistoricosPersonaModificadosPorMi")
                        .HasForeignKey("UsuarioModificoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoPlanilla", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Planilla", "Planilla")
                        .WithMany("HistoricosPlanillaSueldos")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Usuario", "UsuarioModifico")
                        .WithMany("HistoricosPlanillaModificadosPorMi")
                        .HasForeignKey("UsuarioModificoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planilla");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoTrabajador", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("HistoricosTrabajador")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Usuario", "UsuarioModifico")
                        .WithMany("HistoricosTrabajadorModificadosPorMi")
                        .HasForeignKey("UsuarioModificoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trabajador");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoTrabajadorPlanilla", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.TrabajadorPlanilla", "TrabajadorPlanilla")
                        .WithMany("HistoricoTrabajadorPlanillas")
                        .HasForeignKey("IdTrabajadorPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Usuario", "UsuarioModifico")
                        .WithMany("HistoricosTrabajadorPlanillaModificadosPorMi")
                        .HasForeignKey("UsuarioModificoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrabajadorPlanilla");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HistoricoUsuario", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Usuario", "Usuario")
                        .WithMany("HistoricosComoTitular")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Usuario", "UsuarioModifico")
                        .WithMany("HistoricosModificadosPorMi")
                        .HasForeignKey("UsuarioModificoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioModifico");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Horario", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Horarios")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.HuellaDactilar", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Persona", "Persona")
                        .WithMany("HuellaDactilars")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.LogAcceso", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Usuario", "Usuario")
                        .WithMany("LogAccesos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Persona", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "Nacionalidad")
                        .WithMany("Personas")
                        .HasForeignKey("IdNacionalidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nacionalidad");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Planilla", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "TipoPlanilla")
                        .WithMany("TiposPlanilla")
                        .HasForeignKey("IdTipoPlanilla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPlanilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Solicitud", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "EstadoSolicitud")
                        .WithMany("EstadosSolicitud")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Trabajador", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Cargo", "Cargo")
                        .WithMany("Trabajadors")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Persona", "Persona")
                        .WithOne("Trabajador")
                        .HasForeignKey("BackendCoopSoft.Models.Trabajador", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.TrabajadorPlanilla", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Planilla", "Planilla")
                        .WithMany("TrabajadorPlanillas")
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("TrabajadorPlanillas")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planilla");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.TrabajadorPlanillaValor", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Concepto", "Concepto")
                        .WithMany("TrabajadorPlanillaValores")
                        .HasForeignKey("IdConcepto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.TrabajadorPlanilla", "TrabajadorPlanilla")
                        .WithMany("TrabajadorPlanillaValors")
                        .HasForeignKey("IdTrabajadorPlanilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concepto");

                    b.Navigation("TrabajadorPlanilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Usuario", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("BackendCoopSoft.Models.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Licencia", b =>
                {
                    b.HasOne("BackendCoopSoft.Models.Clasificador", "EstadoLicencia")
                        .WithMany("EstadosLicencia")
                        .HasForeignKey("IdEstadoLicencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Clasificador", "TipoLicencia")
                        .WithMany("Licencias")
                        .HasForeignKey("IdTipoLicencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendCoopSoft.Models.Trabajador", "Trabajador")
                        .WithMany("Licencias")
                        .HasForeignKey("IdTrabajador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoLicencia");

                    b.Navigation("TipoLicencia");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Cargo", b =>
                {
                    b.Navigation("Trabajadors");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Clasificador", b =>
                {
                    b.Navigation("EstadosLicencia");

                    b.Navigation("EstadosSolicitud");

                    b.Navigation("Faltas");

                    b.Navigation("Licencias");

                    b.Navigation("MetodosCalculoConcepto");

                    b.Navigation("NaturalezasConcepto");

                    b.Navigation("PeriodosPago");

                    b.Navigation("Personas");

                    b.Navigation("TiposContrato");

                    b.Navigation("TiposPlanilla");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Concepto", b =>
                {
                    b.Navigation("TrabajadorPlanillaValores");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Falta", b =>
                {
                    b.Navigation("HistoricoFaltas");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Oficina", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Persona", b =>
                {
                    b.Navigation("HistoricoPersonas");

                    b.Navigation("HuellaDactilars");

                    b.Navigation("Trabajador");

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Planilla", b =>
                {
                    b.Navigation("HistoricosPlanillaSueldos");

                    b.Navigation("TrabajadorPlanillas");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Trabajador", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Capacitaciones");

                    b.Navigation("Contratos");

                    b.Navigation("Faltas");

                    b.Navigation("FormacionesAcademicas");

                    b.Navigation("HistoricosTrabajador");

                    b.Navigation("Horarios");

                    b.Navigation("Licencias");

                    b.Navigation("Solicitudes");

                    b.Navigation("TrabajadorPlanillas");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.TrabajadorPlanilla", b =>
                {
                    b.Navigation("HistoricoTrabajadorPlanillas");

                    b.Navigation("TrabajadorPlanillaValors");
                });

            modelBuilder.Entity("BackendCoopSoft.Models.Usuario", b =>
                {
                    b.Navigation("HistoricosComoTitular");

                    b.Navigation("HistoricosFaltaModificadosPorMi");

                    b.Navigation("HistoricosModificadosPorMi");

                    b.Navigation("HistoricosPersonaModificadosPorMi");

                    b.Navigation("HistoricosPlanillaModificadosPorMi");

                    b.Navigation("HistoricosTrabajadorModificadosPorMi");

                    b.Navigation("HistoricosTrabajadorPlanillaModificadosPorMi");

                    b.Navigation("LogAccesos");
                });
#pragma warning restore 612, 618
        }
    }
}
